[package]
name = "gamecode"
version = "0.1.1"
edition = "2024"
description = "AI assistant using MCP and Game and Text UIs"
license = "MIT"
authors = ["Ed Sweeney <ed@onextent.com>"]

[dependencies]
# Bevy for visualization
bevy = "0.15" # Upgrading to Bevy 0.15
 
# UI components - version compatible with Bevy 0.15
bevy_egui = "0.33" # Compatible with Bevy 0.15
egui = "0.31" # Keep in sync with bevy_egui
egui_extras = "0.31" # Keep in sync with egui

# Agent and LLM requirements - using modular gamecode architecture
gamecode-backend = { git = "https://github.com/navicore/gamecode-backend.git" }
gamecode-bedrock = { git = "https://github.com/navicore/gamecode-bedrock.git" }
gamecode-tools = { git = "https://github.com/navicore/gamecode-tools.git" }
uuid = { version = "1.8", features = ["v4", "serde"] }
tokio = { version = "1.32", features = ["full"] }
async-trait = "0.1"

# Core functionality
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
anyhow = "1.0"
thiserror = "2.0"

# Utilities
regex = "1.9"
once_cell = "1.18"
directories = "6.0"
tracing = "0.1"
tracing-subscriber = "0.3"
rand = "0.9"
futures = "0.3"
